#!/usr/bin/openrc-run
# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

supervisor=supervise-daemon
command="/usr/bin/navidrome"
command_args="--configfile \"/var/lib/navidrome/navidrome.toml\""
supervise_daemon_args="-d /var/lib/navidrome -1 /var/lib/navidrome/navidrome.log -2 /var/lib/navidrome/navidrome.err.log"

description="Navidrome Server"
respawn_delay=5

command_user=navidrome:navidrome

depend() {
	need net;
}
