#!/usr/bin/openrc-run
# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

supervisor=supervise-daemon
command="/usr/sbin/netdata"
command_args="-D $EXTRA_OPTS"
supervise_daemon_args="-d /var/cache/netdata"

description="Real time performance monitoring"
respawn_delay=5

command_user=netdata:netdata

depend() {
	need net;
	want nginx;
}
